#include <zephyr.h>

#define MODULE peripheral_module
LOG_MODULE_REGISTER(MODULE, 4);


#if defined(CONFIG_THINGY_ENABLE)
#define THINGY_BUFFER_SIZE CONFIG_THINGY_DATA_BUFFER_SIZE
#define THINGY_SAMPLE_RATE CONFIG_THINGY_SAMPLE_RATE
#define THINGY_SAMPLE_TO_SEND CONFIG_THINGY_SAMPLE_TO_SEND
#endif